const rules = {
  staff: {
    static: [
      'APPLICATION_OVERVIEW/FILTERS:VIEW',
      'APPLICATION_OVERVIEW/QUEUE_BAR:VIEW',
      'APPLICATION_FLOW_MEETING_PAST_INVITATION:VIEW',
      'APPLICATION_FLOW_SEND_INVITATION:VIEW',
      'APPLICATION_FLOW_MEETING_NOTES:VIEW',
      'APPLICATION_FLOW_ALL_EVALUATION:VIEW',
      'TIMELINE/CREATE_PRIVATE_COMMENT:VIEW',
      'TIMELINE/EMAIL_THREAD_META:VIEW',
      'USER_PROFILE/SOCIAL_MEDIA:VIEW',
      'COMMUNITY/FILTER:VIEW'
    ],
    dynamic: [
      'APPLICATION_FLOW_ASSIGN_INTERVIEWER:EDIT',
      'APPLICATION_FLOW_MEETING_CHANGES:VIEW',
      'APPLICATION_FLOW_START_MEETING_NOT_HOST:VIEW',
      'APPLICATION_FLOW_AVAILABILITIES_CHANGES:VIEW',
      'APPLICATION_FLOW_ASSIGNED_EVALUATORS:EDIT',
      'APPLICATION_FLOW_FUNNEL_DRAFT_DELETE:EDIT',
      'APPLICATION_FLOW_APPLICATION_TYPE:EDIT',
      'STARTUP_FILE:VIEW',
      'APPLICATION/DECIDE_ROUND:VIEW',
      'TASK/TASK:DELETE',
      'INDUSTRIES:VIEW',
      'TAGS:VIEW'
    ]
  },
  coach: {
    static: [
      'APPLICATION_OVERVIEW/FILTERS:VIEW',
      'APPLICATION_OVERVIEW/QUEUE_BAR:VIEW',
      'APPLICATION_FLOW_MEETING_PAST_INVITATION:VIEW',
      'APPLICATION_FLOW_SEND_INVITATION:VIEW',
      'APPLICATION_FLOW_MEETING_NOTES:VIEW',
      'APPLICATION_FLOW_ALL_EVALUATION:VIEW',
      'TIMELINE/CREATE_PRIVATE_COMMENT:VIEW',
      'TIMELINE/EMAIL_THREAD_META:VIEW',
      'STARTUP/ASSIGNATION_MEMBERS:EDIT',
      'USER_PROFILE/SOCIAL_MEDIA:VIEW',
      'COMMUNITY/FILTER:VIEW'
    ],
    dynamic: [
      'APPLICATION_FLOW_ASSIGN_INTERVIEWER:EDIT',
      'APPLICATION_FLOW_MEETING_CHANGES:VIEW',
      'APPLICATION_FLOW_START_MEETING_NOT_HOST:VIEW',
      'APPLICATION_FLOW_AVAILABILITIES_CHANGES:VIEW',
      'APPLICATION_FLOW_ASSIGNED_EVALUATORS:EDIT',
      'APPLICATION_FLOW_FUNNEL_DRAFT_DELETE:EDIT',
      'APPLICATION_FLOW_APPLICATION_TYPE:EDIT',
      'STARTUP_FILE:VIEW',
      'APPLICATION/DECIDE_ROUND:VIEW',
      'TASK/TASK:DELETE',
      'INDUSTRIES:VIEW',
      'TAGS:VIEW'
    ]
  },
  evaluator: {
    static: [
      'APPLICATION_OVERVIEW/FILTERS:VIEW',
      'APPLICATION_OVERVIEW/QUEUE_BAR:VIEW',
      'TIMELINE/CREATE_PRIVATE_COMMENT:VIEW',
      'TIMELINE/EMAIL_THREAD_META:VIEW',
      'USER_PROFILE/SOCIAL_MEDIA:VIEW',
      'COMMUNITY/FILTER:VIEW'
    ],
    dynamic: ['TASK/TASK:DELETE', 'INDUSTRIES:VIEW', 'TAGS:VIEW']
  },
  expert: {
    static: [
      'APPLICATION_OVERVIEW/FILTERS:VIEW',
      'APPLICATION_OVERVIEW/QUEUE_BAR:VIEW',
      'TIMELINE/CREATE_PRIVATE_COMMENT:VIEW',
      'TIMELINE/EMAIL_THREAD_META:VIEW',
      'USER_PROFILE/SOCIAL_MEDIA:VIEW',
      'COMMUNITY/FILTER:VIEW'
    ],
    dynamic: ['TASK/TASK:DELETE', 'INDUSTRIES:VIEW', 'TAGS:VIEW']
  },
  mentor: {
    static: [
      'APPLICATION_OVERVIEW/FILTERS:VIEW',
      'APPLICATION_OVERVIEW/QUEUE_BAR:VIEW',
      'COACHING_SESSION/SETTINGS:VIEW',
      'TIMELINE/CREATE_PRIVATE_COMMENT:VIEW',
      'TIMELINE/EMAIL_THREAD_META:VIEW',
      'USER_PROFILE/SOCIAL_MEDIA:VIEW',
      'COMMUNITY/FILTER:VIEW'
    ],
    dynamic: ['TASK/TASK:DELETE', 'INDUSTRIES:VIEW', 'TAGS:VIEW']
  },
  subadmin: {
    static: [
      'APPLICATION_OVERVIEW/FILTERS:VIEW',
      'APPLICATION_OVERVIEW/QUEUE_BAR:VIEW',
      'APPLICATION_FLOW_SEND_INVITATION:VIEW',
      'TIMELINE/CREATE_PRIVATE_COMMENT:VIEW',
      'TIMELINE/EMAIL_THREAD_META:VIEW',
      'APPLICATION/DOWNLOAD_APPLICATION_CTA:VIEW',
      'COACHING_SESSION/SETTINGS:VIEW',
      'COURSE:CREATE',
      'FEEDBACK:CREATE',
      'COMMUNITY/FILTER:VIEW'
    ],
    dynamic: [
      'APPLICATION_OVERVIEW/BATCH/ACTION_CTAS:VIEW',
      'APPLICATION_FLOW_ASSIGN_INTERVIEWER:EDIT',
      'APPLICATION_FLOW_MEETING_CHANGES:VIEW',
      'APPLICATION_FLOW_MEETING_PAST_INVITATION:VIEW',
      'APPLICATION_FLOW_MEETING_NOTES:VIEW',
      'APPLICATION_FLOW_START_MEETING_NOT_HOST:VIEW',
      'APPLICATION_FLOW_AVAILABILITIES_CHANGES:VIEW',
      'APPLICATION_FLOW_ASSIGNED_EVALUATORS:EDIT',
      'APPLICATION_FLOW_ALL_EVALUATION:VIEW',
      'APPLICATION_FLOW_FUNNEL_DRAFT_DELETE:EDIT',
      'APPLICATION_FLOW_APPLICATION_TYPE:EDIT',
      'FUNNEL:EDIT',
      'STARTUP_FILE:VIEW',
      'APPLICATION/DECIDE_ROUND:VIEW',
      'STARTUP/ASSIGNATION_MEMBERS:EDIT',
      'STARTUP/NAME:EDIT',
      'FORM:EDIT',
      'TASK/TASK:DELETE',
      'USER_PROFILE/SOCIAL_MEDIA:VIEW',
      'INDUSTRIES:VIEW',
      'TAGS:VIEW',
      'USER:EDIT'
    ]
  },
  admin: {
    static: [
      'APPLICATION_OVERVIEW/FILTERS:VIEW',
      'APPLICATION_OVERVIEW/QUEUE_BAR:VIEW',
      'APPLICATION_OVERVIEW/BATCH/ACTION_CTAS:VIEW',
      'APPLICATION_FLOW_ASSIGN_INTERVIEWER:EDIT',
      'APPLICATION_FLOW_SEND_INVITATION:VIEW',
      'APPLICATION_FLOW_MEETING_CHANGES:VIEW',
      'APPLICATION_FLOW_MEETING_PAST_INVITATION:VIEW',
      'APPLICATION_FLOW_MEETING_NOTES:VIEW',
      'APPLICATION_FLOW_START_MEETING_NOT_HOST:VIEW',
      'APPLICATION_FLOW_AVAILABILITIES_CHANGES:VIEW',
      'APPLICATION_FLOW_FUNNEL_DRAFT_DELETE:EDIT',
      'APPLICATION_FLOW_APPLICATION_TYPE:EDIT',
      'APPLICATION_FLOW_ASSIGNED_EVALUATORS:EDIT',
      'APPLICATION_FLOW_ALL_EVALUATION:VIEW',
      'TIMELINE/CREATE_PRIVATE_COMMENT:VIEW',
      'TIMELINE/EMAIL_THREAD_META:VIEW',
      'APPLICATION/DOWNLOAD_APPLICATION_CTA:VIEW',
      'COACHING_SESSION/SETTINGS:VIEW',
      'COURSE:CREATE',
      'STARTUP/NAME:EDIT',
      'FORM:EDIT',
      'METRICS/EDIT:VIEW',
      'APPLICATION/DECIDE_ROUND:VIEW',
      'USER_PROFILE/SOCIAL_MEDIA:VIEW',
      'FEEDBACK:CREATE',
      'INDUSTRIES:VIEW',
      'TAGS:VIEW',
      'USER:EDIT',
      'COMMUNITY/FILTER:VIEW'
    ],
    dynamic: [
      'FUNNEL:EDIT',
      'STARTUP_FILE:VIEW',
      'STARTUP/ASSIGNATION_MEMBERS:EDIT',
      'TASK/TASK:DELETE'
    ]
  },
  'admin&coach': {
    static: [
      'APPLICATION_OVERVIEW/FILTERS:VIEW',
      'APPLICATION_OVERVIEW/QUEUE_BAR:VIEW',
      'APPLICATION_OVERVIEW/BATCH/ACTION_CTAS:VIEW',
      'APPLICATION_FLOW_ASSIGN_INTERVIEWER:EDIT',
      'APPLICATION_FLOW_SEND_INVITATION:VIEW',
      'APPLICATION_FLOW_MEETING_CHANGES:VIEW',
      'APPLICATION_FLOW_MEETING_PAST_INVITATION:VIEW',
      'APPLICATION_FLOW_MEETING_NOTES:VIEW',
      'APPLICATION_FLOW_START_MEETING_NOT_HOST:VIEW',
      'APPLICATION_FLOW_AVAILABILITIES_CHANGES:VIEW',
      'APPLICATION_FLOW_FUNNEL_DRAFT_DELETE:EDIT',
      'APPLICATION_FLOW_APPLICATION_TYPE:EDIT',
      'APPLICATION_FLOW_ASSIGNED_EVALUATORS:EDIT',
      'APPLICATION_FLOW_ALL_EVALUATION:VIEW',
      'TIMELINE/CREATE_PRIVATE_COMMENT:VIEW',
      'TIMELINE/EMAIL_THREAD_META:VIEW',
      'APPLICATION/DOWNLOAD_APPLICATION_CTA:VIEW',
      'COACHING_SESSION/SETTINGS:VIEW',
      'COURSE:CREATE',
      'STARTUP/NAME:EDIT',
      'FORM:EDIT',
      'METRICS/EDIT:VIEW',
      'APPLICATION/DECIDE_ROUND:VIEW',
      'USER_PROFILE/SOCIAL_MEDIA:VIEW',
      'FEEDBACK:CREATE',
      'INDUSTRIES:VIEW',
      'TAGS:VIEW',
      'USER:EDIT',
      'COMMUNITY/FILTER:VIEW'
    ],
    dynamic: [
      'FUNNEL:EDIT',
      'STARTUP_FILE:VIEW',
      'STARTUP/ASSIGNATION_MEMBERS:EDIT',
      'TASK/TASK:DELETE'
    ]
  },
  cofounder: {
    dynamic: [
      'STARTUP/NAME:EDIT',
      'PROFILE/BOOK_MEETING_CTA:VIEW',
      'TASK/TASK:DELETE',
      'USER_PROFILE/SOCIAL_MEDIA:VIEW',
      'INDUSTRIES:VIEW',
      'TAGS:VIEW'
    ]
  },

  community_member: {
    static: ['COMMUNITY/FILTER:VIEW'],
    dynamic: [
      'TASK/TASK:DELETE',
      'PROFILE/BOOK_MEETING_CTA:VIEW',
      'USER_PROFILE/SOCIAL_MEDIA:VIEW',
      'INDUSTRIES:VIEW',
      'TAGS:VIEW'
    ]
  }
};

export default rules;
